<a href="https://colab.research.google.com/github/BIDS-CPU/data-science1/blob/main/DC3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sea
import warnings

In [5]:
warnings.filterwarnings('ignore')

In [6]:
df=pd.read_csv('cc_approvals.data')

In [7]:
pd.set_option('display.max_columns',None)

In [8]:
df.sample(3)

b  30.83      0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
632  b  32.42  2.165  y  p   k  ff  0.000  f   f   0  f   g  00120    0  -
340  b  42.75  4.085  u  g  aa   v  0.040  f   f   0  f   g  00108  100  -
9    b  22.08  0.830  u  g   c   h  2.165  f   f   0  t   g  00128    0  +

In [9]:
df.columns.to_list()

['b',
 '30.83',
 '0',
 'u',
 'g',
 'w',
 'v',
 '1.25',
 't',
 't.1',
 '01',
 'f',
 'g.1',
 '00202',
 '0.1',
 '+']

In [10]:
df.dtypes

b         object
30.83     object
0        float64
u         object
g         object
w         object
v         object
1.25     float64
t         object
t.1       object
01         int64
f         object
g.1       object
00202     object
0.1        int64
+         object
dtype: object

In [11]:
df.dtypes.value_counts()

object     12
float64     2
int64       2
dtype: int64

In [12]:
df.isnull().sum()

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [14]:
df.shape

(689, 16)

In [13]:
df.describe()

0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

In [20]:
df.isnull().sum()

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [21]:
df.fillna(df.mean())

b  30.83       0  u  g   w   v  1.25  t t.1  01  f g.1  00202  0.1  +
0    a  58.67   4.460  u  g   q   h  3.04  t   t   6  f   g  00043  560  +
1    a  24.50   0.500  u  g   q   h  1.50  t   f   0  f   g  00280  824  +
2    b  27.83   1.540  u  g   w   v  3.75  t   t   5  t   g  00100    3  +
3    b  20.17   5.625  u  g   w   v  1.71  t   f   0  f   s  00120    0  +
4    b  32.08   4.000  u  g   m   v  2.50  t   f   0  t   g  00360    0  +
..  ..    ...     ... .. ..  ..  ..   ... ..  ..  .. ..  ..    ...  ... ..
684  b  21.08  10.085  y  p   e   h  1.25  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.00  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.00  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.04  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.29  f   f   0  t   g  00000    0  -

[689 rows x 16 columns]

In [27]:
for i in df.columns:
  if df[i].dtypes=='object':
    df=df.fillna(df[i].value_counts().index[0])

In [28]:
df.isnull().sum()

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
lr=LabelEncoder()

In [31]:
for i in df.columns:
  if df[i].dtypes=='object':
    df[i]=lr.fit_transform(df[i])

In [32]:
from sklearn.model_selection import train_test_split

In [34]:
x=df.iloc[:,0:13]
y=df.iloc[:,13]

In [79]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.33)

In [80]:
X_train

b  30.83       0  u  g   w  v    1.25  t  t.1  01  f  g.1
382  1    319   4.250  3  3   6  3   5.000  0    0   0  1    0
137  1     31   9.500  2  1  13  8   1.625  1    1   6  1    0
346  2    114   4.500  3  3   2  1   2.500  0    0   0  0    0
326  0    240   3.500  2  1   7  1   0.500  0    0   0  0    2
33   1     70  10.750  2  1  11  8   0.415  1    1   5  1    0
..  ..    ...     ... .. ..  .. ..     ... ..  ...  .. ..  ...
71   1    222   5.000  2  1   3  8  13.500  1    0   0  1    0
106  1     94  11.000  3  3   1  8   4.500  1    0   0  0    0
270  2    170   2.500  2  1   2  8   1.250  0    0   0  1    0
435  2     38   0.585  2  1   6  3   0.000  0    1   3  0    0
102  2     94  12.000  2  1   9  8   2.250  1    1   2  1    0

[461 rows x 13 columns]

In [81]:
y_train

382      0
137     10
346     67
326    167
33       0
      ... 
71     166
106     37
270     95
435    111
102     37
Name: 00202, Length: 461, dtype: int64

In [82]:
from sklearn.preprocessing import MinMaxScaler

In [83]:
ms=MinMaxScaler(feature_range=(0,1))

In [84]:
rxt=ms.fit_transform(X_train)
rxte=ms.fit_transform(X_test)

In [85]:
from sklearn.linear_model import LogisticRegression

In [86]:
lr=LogisticRegression()

In [87]:
lr.fit(X_train,y_train)

LogisticRegression()

In [88]:
lr.get_params

<bound method BaseEstimator.get_params of LogisticRegression()>

In [89]:
lr.intercept_

array([ 8.48234855e-02, -1.07824468e-02,  2.04032306e-04, -1.67387046e-02,
       -8.45960055e-03, -1.62228845e-02,  1.91954257e-02, -1.72777400e-02,
        7.64695525e-03,  4.92574150e-03, -6.82091903e-04, -1.32963782e-02,
        1.39560844e-02, -1.52169878e-02, -1.42928440e-02, -1.50398704e-02,
       -2.86787930e-03, -9.93689349e-03,  5.83225267e-02,  9.90556165e-03,
       -3.07031041e-03, -1.25840249e-02, -1.00448726e-02,  3.98400327e-04,
       -4.28384566e-03,  4.34536166e-02,  7.04853547e-03,  1.39643823e-02,
        8.60286198e-03,  3.28203444e-03, -1.38054742e-02,  9.42117495e-03,
        9.66340200e-03,  4.13512507e-02, -1.23943463e-02, -2.76572170e-03,
       -1.45634434e-02, -3.17523280e-03, -7.09271287e-05, -1.52391860e-02,
        6.43839649e-02, -7.79132271e-03, -1.50837893e-03, -3.79782781e-03,
       -4.55519289e-03, -3.11613929e-03, -1.03616636e-03, -1.20174239e-02,
       -1.90161849e-03,  4.17452439e-02, -6.28405193e-03, -1.06142917e-02,
       -7.86089870e-03,  

In [90]:
from sklearn.metrics import confusion_matrix

In [91]:
ypredict1=lr.predict(rxte)

In [92]:
acc=lr.score(rxte,y_test)
acc

0.039473684210526314

In [94]:
print("Accuracy of logistic regression classifier: ", lr.score(rxte, y_test))


Accuracy of logistic regression classifier:  0.039473684210526314


In [78]:
print(confusion_matrix(y_test,ypredict1))

[[3 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
